=== FernandoFaria/legendtv/trunk/LegendTV/src/com/googlecode/legendtv/intf/menus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:ltv="http://www.googlecode.com/p/legendtv/Menus"
 		targetNamespace="http://www.googlecode.com/p/legendtv/Menus"
 		elementFormDefault="qualified">

	<!-- Root element of the menu -->
 	<element name="menuList">
	    <complexType>
	    	<sequence>
	    		<element name="menu" type="ltv:menu" minOccurs="0" maxOccurs="unbounded"/>
	    	</sequence>
	    </complexType>
    </element>

    <complexType name="menu">
    	<sequence>
    		<element name="title" type="string" minOccurs="1"/>
    		<element name="optionList" type="ltv:optionList" minOccurs="0"/>
    	</sequence>
    	<attribute name="name" type="string" use="required"/>
    	<attribute name="presentation" type="ltv:presentationType" default="normal"/>
    	<attribute name="backTo" type="string" use="optional"/>
    </complexType>
    
  	<simpleType name="presentationType">
  		<annotation>
  			<appinfo>
  				<typesafeEnumClass name="PresentationType"/>
  			</appinfo>
  		</annotation>
		<restriction base="string">
			<enumeration value="normal"/>
			<enumeration value="dialog"/>
		</restriction>
	</simpleType>

    <complexType name="optionList">
    	<sequence>
    		<element name="option" type="ltv:option" minOccurs="0" maxOccurs="unbounded"/>
    		<element name="dynamicOption" type="ltv:dynamicOption" minOccurs="0" maxOccurs="unbounded"/>
    	</sequence>
   	</complexType>
   	
   	<complexType name="option">
   		<sequence>
   			<element name="caption" type="string" minOccurs="1"/>
   			<element name="action" type="ltv:action" minOccurs="1"/>
   		</sequence>
   		<attribute name="name" type="string" use="required"/>
   		<attribute name="placeBefore" type="string" />
   		<attribute name="placeAfter" type="string" />
   	</complexType>
   	
   	<complexType name="dynamicOption">
   		<attribute name="generator" type="string"/>
   	</complexType>
   	
   	<complexType name="action">
   		<attribute name="type" type="ltv:actionType">
   			
   		</attribute>
   		<attribute name="target" type="string"/>
   	</complexType>
   	
   	<simpleType name="actionType">
   		<annotation>
  			<appinfo>
  				<typesafeEnumClass name="ActionType"/>
  			</appinfo>
  		</annotation>
		<restriction base="string">
			<enumeration value="menu"/>
			<enumeration value="method"/>
		</restriction>
	</simpleType>
</schema>

=== FernandoFaria/legendtv/LegendTV/src/com/googlecode/legendtv/intf/menus.xml
<?xml version="1.0" encoding="UTF-8"?>
<menuList xmlns="http://www.googlecode.com/p/legendtv/Menus"
	   	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   	  xsi:schemaLocation="http://www.googlecode.com/p/legendtv/Menus menus.xsd">
	<!-- Main Menu
		 =========
		 1) Manage recordings
		 2) Control another session
		 3) Change settings
		 4) Monitor system status
	  -->
	<menu name="MainMenu">
		<title>Main Menu</title>
		<optionList>
			<option name="recordings">
				<caption>Manage recordings</caption>
				<action type="menu" target="RecordingManagement"/>
			</option>
			<option name="sessionControl" placeAfter="recordings">
				<caption>Control another session</caption>
				<action type="menu" target="ControlSession"/>
			</option>
			<option name="settings" placeAfter="sessionControl">
				<caption>Change settings</caption>
				<action type="menu" target="Settings"/>
			</option>
			<option name="systemMonitor" placeAfter="settings">
				<caption>Monitor system status</caption>
				<action type="menu" target="MonitorSystem"/>
			</option>
			<dynamicOption generator="com.googlecode.legendtv.plugins.MenuGenerator"/>
		</optionList>
	</menu>
	<menu name="RecordingManagement" backTo="MainMenu">
		<title>Manage Recordings</title>
		<optionList>
			<option name="viewRecordings">
				<caption>View available recordings</caption>
				<action type="menu" target="AvailableRecordings"/>
			</option>
			<option name="viewSchedule" placeAfter="viewRecordings">
				<caption>View recording schedule</caption>
				<action type="menu" target="RecordingSchedule"/>
			</option>
			<option name="scheduleRecordings" placeAfter="viewSchedule">
				<caption>Schedule a recording</caption>
				<action type="menu" target="ScheduleRecordingType"/>
			</option>
			<dynamicOption generator="com.googlecode.legendtv.intf.generators.PluginsMenu"/>
		</optionList>
	</menu>
	<menu name="ControlSession" backTo="MainMenu">
		<title>Control Another Session</title>
		<optionList>
			<dynamicOption generator="com.googlecode.legendtv.intf.generators.SessionControlMenu"/>
		</optionList>
	</menu>
	<menu name="Settings" backTo="MainMenu">
		<title>Change Settings</title>
		<optionList>
			<dynamicOption generator="com.googlecode.legendtv.intf.generators.SettingsMenu"/>
		</optionList>
	</menu>
	<menu name="MonitorSystem" backTo="MainMenu">
		<title>Monitor System</title>
		<!-- To Be Completed -->
	</menu>
	<menu name="AvailableRecordings" backTo="RecordingManagement">
		<title>View Available Recordings</title>
		<optionList>
			<dynamicOption generator="com.googlecode.legendtv.intf.generators.RecordingList"/>
		</optionList>
	</menu>
	<menu name="RecordingSchedule" backTo="RecordingManagement">
		<title>View Recording Schedule</title>
		<optionList>
			<dynamicOption generator="com.googlecode.legendtv.intf.generators.RecordingSchedule"/>
		</optionList>
	</menu>
	<menu name="ScheduleRecordingType" presentation="dialog" backTo="RecordingManagement">
		<title>What would you like to record?</title>
		<optionList>
			<option name="recordShow">
				<caption>Record a show</caption>
				<action type="menu" target="RecordShow"/>
			</option>
			<option name="recordMovie" placeAfter="recordShow">
				<caption>Record a movie</caption>
				<action type="menu" target="RecordMovie"/>
			</option>
		</optionList>
	</menu>
	<menu name="RecordShow">
		<title>Record a Show</title>
		<!-- To Be Completed -->
	</menu>
	<menu name="RecordShow">
		<title>Record a Movie</title>
		<!-- To Be Completed -->
	</menu>
</menuList>
